server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    '[com.sk.msa]': DEBUG
#    org:
#      hibernate:
#        SQL: ERROR
#        type:
#          descriptor:
#            sql:
#              BasicBinder: ERROR
#      springframework:
#        data:
#          jpa: ERROR
    
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bff-base
    username: bff
    password: bff123$%^
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      max-lifetime: 60000
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: 6379
#      password: XMGmWugvAsY0JBhIgKtTJ0hDPHOiE6CJ
      ssl: 
        enabled: false
    
application:
  name: "REST-API-BASE"
  log:
    custom-headers:
      - "X-BFF-User"
      - "X-Bff-Tid"
      - "X-SKR-UI-Menu"
    hiddens:
    - 'userPassword'
    - 'userPasswordRenew'
  health:
    url: http://localhost:8080/actuator/health
    timeout: 5000
    