package com.sk.skala.stockapi.config;

public enum Error {
	//@formatter:off
	
	SYSTEM_ERROR(9000, "SYSTEM_ERROR"),
	
	// codes should be shared with UI
	NOT_AUTHENTICATED(9001, "NOT_AUTHENTICATED"),
	NOT_AUTHORIZED(9002, "NOT_AUTHORIZED"),
	SESSION_EXPIRED(9003, "SESSION_EXPIRED"),
	SESSION_NOT_FOUND(9004, "SESSION_NOT_FOUND"),
	
	UNCAUGHT_EXCEPTION(9005, "UNCAUGHT_EXCEPTION"),
	DATA_DUPLICATED(9006, "DATA_DUPLICATED"),
	PARAMETER_MISSED(9007, "PARAMETER_MISSED"),
	DATA_NOT_FOUND(9008, "DATA_NOT_FOUND"),
	CONNECTION_FAILED(9009, "CONNECTION_FAILED"),
	WRONG_RESPONSE(9010, "WRONG_RESPONSE"),
	INVALID_EXCEL_FORMAT(9011, "INVALID_EXCEL_FORMAT"),
	
	INVALID_ID_OR_PASSWORD(9012, "INVALID_ID_OR_PASSWORD"),
	EXPIRED_PASSWROD(9013, "EXPIRED_PASSWROD"),
	WRONG_PASSWROD_TRIES(9014, "WRONG_PASSWROD_TRIES"),
	ACCOUNT_ID_EXISTS(9015, "ACCOUNT_ID_EXISTS"),
	INVALID_PASSWORD_PATTERN(9016, "INVALID_PASSWORD_PATTERN"),
	INVALID_USER_GROUP(9017, "INVALID_USER_GROUP"),
	
	SAGA_EXECUTION_FAILED(9018, "SAGA_EXECUTION_FAILED"),
	SAGA_TRANSACTION_IVALID(9019, "SAGA_TRANSACTION_IVALID"),
	SAGA_API_ERROR(9020, "SAGA_API_ERROR"),
	INVALID_DATA_STATUS(9021, "INVALID_DATA_STATUS"),
	INVALID_DATA_ID(9022, "INVALID_DATA_ID"),
	
	CODE_MISSED_IN_CODE_GROUP(9023, "CODE_MISSED_IN_CODE_GROUP"),
	INVALID_AUTH_CODE(9024, "INVALID_AUTH_CODE"),
	API_NOT_ACCESSIBLE(9025, "API_NOT_ACCESSIBLE"),
	
	INVALID_SESSION_ID(9026, "INVALID_SESSION_ID"),

	UNDEFINED_ERROR(9999, "UNDEFINED_ERROR");
	
	//@formatter:on

	private final int code;
	private final String message;

	Error(int code, String message) {
		this.code = code;
		this.message = message;
	}

	public int getCode() {
		return code;
	}

	public String getMessage() {
		return message;
	}
}